### ISSUE TITLE
Select element shouldn't have the same shadow rendering as input element

### ISSUE THREAD

**Issue by aaronshekey** [primer/forms#3]
Something that's been bugging this designer. `select` elements are generally rendered as buttons, since they don't take direct text input.

This is consistent throughout browsers / operating systems that haven't been completely flattened. I'd suggest simply flipping the inset shadow on `select`s to be consistent with browser behavior while maintaining the GitHub aesthetic.

**Current**
This has the same styling as a text input.
![primer-inset](https://cloud.githubusercontent.com/assets/1369864/18722874/f2e51644-7ffb-11e6-9dda-520712bf7ac0.png)

**Proposed**
Simply flipping this will render this closer to a button, mimicking other browser / os behavior.
![primer-suggested](https://cloud.githubusercontent.com/assets/1369864/18722887/02ccf1d0-7ffc-11e6-94d9-f79fe2c9487e.png)

**Safari**
![mac-safari](https://cloud.githubusercontent.com/assets/1369864/18722755/8fe077dc-7ffb-11e6-87b8-ef4252b4808a.png)

**Chrome**
![mac-chrome](https://cloud.githubusercontent.com/assets/1369864/18722757/8fea388a-7ffb-11e6-8d87-243175a321c5.png)

**Firefox**
![mac-firefox](https://cloud.githubusercontent.com/assets/1369864/18722756/8fea0f0e-7ffb-11e6-950c-a515acb17003.png)
## 

@primer/design-systems

**Comment by mdo** [comment]
What about screenshots of how they show on Windows? :grin:

**Comment by aaronshekey** [comment]
Windows are totally flat:

**Windows IE11**
![windows-ie11](https://cloud.githubusercontent.com/assets/1369864/18723154/1fd599e8-7ffd-11e6-9ce8-080f95ec4b03.png)

**Windows Chrome**
![windows-chrome](https://cloud.githubusercontent.com/assets/1369864/18723153/1fd3bfc4-7ffd-11e6-960a-b1c8e8ed7c1e.png)

**Windows Firefox**
![windows-firefox](https://cloud.githubusercontent.com/assets/1369864/18723152/1fd250ee-7ffd-11e6-8bcc-ed7cdf761363.png)

If we were to go totally flat, and consistent with Windows, we should remove all shadows. I don't think we should do this :smile:. To be consistent within GitHub's aesthetic, we should consider treating `select` as buttons.
